name: Deploy Backend (Cloud Run)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch: {}

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: ${{ secrets.REGION }}
      REPO: ${{ secrets.REPO }}
      BACKEND_SERVICE: ${{ secrets.BACKEND_SERVICE }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      IMAGE: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/backend:${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker auth
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build image
        working-directory: backend
        run: docker build -t "$IMAGE" .

      - name: Push image
        run: docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$BACKEND_SERVICE" \
            --image="$IMAGE" \
            --region="$REGION" \
            --allow-unauthenticated \
            --port=8080 \
            --update-secrets=MONGO_URI=MONGODB_URI:latest,JWT_SECRET=JWT_SECRET:latest \
            --set-env-vars=NODE_ENV=production,CORS_ORIGIN="$FRONTEND_URL"

      - name: Health check
        run: curl -fsS "${{ secrets.BACKEND_URL }}/health"
